
          
name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x

        # Run tests
        - name: Test
          run: dotnet test

        # Generate the website
        - name: Publish
          run: |
            dotnet publish ZabitaWEB/Server/ZabitaWEB.Server.csproj -c Release -o release --nologo        
        - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
          run: sed -i 's/<base href="\/" \/>/<base href="\/ZabitaWEB\/" \/>/g' release/wwwroot/index.html
            # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
        - name: Add .nojekyll file
          run: touch release/wwwroot/.nojekyll
        - name: Commit wwwroot to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: release/wwwroot
