name: DeployToGitHubPages
env:
  PUBLISH_DIR: ZabitaWEB/ZabitaWEB/Server
# Controls when the action will run
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish app
      run: dotnet publish -c Release -o release


    - name: GitHub Pages
            # You may pin to the exact commit or the version.
            # uses: crazy-max/ghaction-github-pages@db4476a01402e1a7ce05f41832040eef16d14925
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:

        repo: ZabitaWEB
              # Git branch where assets will be deployed
        target_branch: gh-pages
              # Create incremental commit instead of doing push force

              # Build directory to deploy
        build_dir: public
                # The committer name and email address

    env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
        

     
